apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
    name: recruiting-bot-secrets
    namespace: recruiting-bot
spec:
    resyncInterval: 60
    managedSecretReference:
        secretName: recruiting-bot-secrets
        secretNamespace: recruiting-bot
        creationPolicy: Owner
    authentication:
        universalAuth:
            secretsScope:
                projectSlug: recruiting-bot-n0oy
                envSlug: prod
                secretsPath: /
            credentialsRef:
                secretName: infisical-auth
                secretNamespace: recruiting-bot
